// Generates src/data/worldMap.ts (the SVG country paths for the homepage map)
// from the source GeoJSON + intervention iso3 list in scripts/map-src/.
//
// Run:  node scripts/gen-map.mjs
//
// To refresh the source data from the QGIS project (needs GDAL / ogr2ogr):
//   ogr2ogr -f GeoJSON -select "name,iso3" -simplify 0.08 \
//     scripts/map-src/global_south.geojson "<path>/Global south_clip.gpkg"
// then regenerate scripts/map-src/intervention-iso3.json from the iso3 field of
// "Catalyst Intervention Countries_clip.gpkg" (see scripts/README-map.md).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(here, "map-src");
const OUT = path.join(here, "..", "src", "data", "worldMap.ts");

const south = JSON.parse(fs.readFileSync(path.join(SRC, "global_south.geojson"), "utf8"));
const workedIso = new Set(JSON.parse(fs.readFileSync(path.join(SRC, "intervention-iso3.json"), "utf8")));

// ---- Robinson projection (linear interpolation of the standard 5-degree table) ----
const AA = [1,0.9986,0.9954,0.9900,0.9822,0.9730,0.9600,0.9427,0.9216,0.8962,0.8679,0.8350,0.7986,0.7597,0.7186,0.6732,0.6213,0.5722,0.5322];
const BB = [0,0.0620,0.1240,0.1860,0.2480,0.3100,0.3720,0.4340,0.4958,0.5571,0.6176,0.6769,0.7346,0.7903,0.8435,0.8936,0.9394,0.9761,1.0000];
function robinson(lon, lat) {
  const phi = Math.abs(lat);
  const i = Math.min(17, Math.floor(phi / 5));
  const t = (phi - i * 5) / 5;
  const X = AA[i] + (AA[i + 1] - AA[i]) * t;
  const Y = BB[i] + (BB[i + 1] - BB[i]) * t;
  const x = 0.8487 * X * (lon * Math.PI / 180);
  let y = 1.3523 * Y;
  if (lat < 0) y = -y;
  return [x, y];
}

const countries = south.features.map((f) => ({
  name: f.properties.name,
  iso3: (f.properties.iso3 || "").trim(),
  worked: workedIso.has((f.properties.iso3 || "").trim()),
  geom: f.geometry,
}));

// Warn if any intervention country is missing from the display layer.
const present = new Set(countries.map((c) => c.iso3));
for (const iso of workedIso) if (!present.has(iso)) console.warn("WARNING: intervention iso3 not in display layer:", iso);

function ringsOf(geom) {
  const rings = [];
  const push = (poly) => { for (const ring of poly) rings.push(ring); };
  if (geom.type === "Polygon") push(geom.coordinates);
  else if (geom.type === "MultiPolygon") for (const poly of geom.coordinates) push(poly);
  return rings;
}

// Pass 1: project everything to find global bounds (skip antimeridian-spanning rings).
let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity, skipped = 0;
for (const c of countries) {
  for (const ring of ringsOf(c.geom)) {
    const lons = ring.map((p) => p[0]);
    if (Math.max(...lons) - Math.min(...lons) > 180) { skipped++; continue; }
    for (const [lon, lat] of ring) {
      const [x, y] = robinson(lon, lat);
      if (x < minX) minX = x; if (x > maxX) maxX = x;
      if (y < minY) minY = y; if (y > maxY) maxY = y;
    }
  }
}

const W = 1000;
const scale = W / (maxX - minX);
const H = +((maxY - minY) * scale).toFixed(1);
const px = (x) => +(((x - minX) * scale)).toFixed(1);
const py = (y) => +(((maxY - y) * scale)).toFixed(1);

function pathFor(geom) {
  const parts = [];
  for (const ring of ringsOf(geom)) {
    const lons = ring.map((p) => p[0]);
    if (Math.max(...lons) - Math.min(...lons) > 180) continue;
    let d = "";
    for (let i = 0; i < ring.length; i++) {
      const [x, y] = robinson(ring[i][0], ring[i][1]);
      d += (i === 0 ? "M" : "L") + px(x) + " " + py(y);
    }
    if (d) parts.push(d + "Z");
  }
  return parts.join("");
}

const rows = countries
  .map((c) => ({ name: c.name, iso3: c.iso3, worked: c.worked, d: pathFor(c.geom) }))
  .filter((c) => c.d.length > 0)
  // draw blue backdrop first, amber (worked) last so hover targets sit above neighbours
  .sort((a, b) => Number(a.worked) - Number(b.worked));

console.log(`countries: ${rows.length}, worked: ${rows.filter((r) => r.worked).length}, viewBox H: ${H}, antimeridian rings skipped: ${skipped}`);

const ts = `// AUTO-GENERATED by scripts/gen-map.mjs — do not edit by hand.
// Source: QGIS "Map for site V2.qgz" layers "Global south_clip" + "Catalyst Intervention Countries_clip".
// Robinson projection; coordinates in a ${W}x${H} viewBox. Regenerate: node scripts/gen-map.mjs
export interface MapCountry {
  name: string;
  iso3: string;
  worked: boolean;
  d: string;
}

export const mapViewBox = "0 0 ${W} ${H}";

export const mapCountries: MapCountry[] = ${JSON.stringify(rows)};
`;

fs.writeFileSync(OUT, ts);
console.log("wrote", path.relative(path.join(here, ".."), OUT), `(${(ts.length / 1024).toFixed(0)} KB)`);
